### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by CristinaRO** [DFE-Digital/claim-additional-payments-for-teaching#1063]
All the links in the first paragraph are currently broken:

https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/master/docs/infrastructure-deployment.md#deployment-process

**Comment by lawrence-forooghian** [comment]
Weird – the same technique of putting the links at the bottom of the document seems to work in `CHANGELOG.md`. I'll take a look, thanks!

**Comment by lawrence-forooghian** [comment]
Opened #1071 to fix this.
