### ISSUE TITLE
Incorrect param in DQT requests

### ISSUE THREAD

**Issue by ethanmills** [DFE-Digital/claim-additional-payments-for-teaching#1365]
https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/8e0a40a356bd6ff1f116e17af7224fad2df9b759/lib/dqt/api/v1/qualified_teaching_status.rb#L12

Hey, I'm looking at using this in some CPD/ECF code. Noticed that the NINO param here doesn't match the postman example, and doesn't work. I think it should be `ni`, right?

**Comment by ethanmills** [comment]
See the line in the API: https://github.com/DFE-Digital/claim-additional-payments-for-teaching-qts-api/blob/master/solution/dqt.api/Functions/QualifiedTeacherStatusService.cs#L54

**Comment by ethanmills** [comment]
I'm also wondering why https://github.com/DFE-Digital/claim-additional-payments-for-teaching/blob/8e0a40a356bd6ff1f116e17af7224fad2df9b759/lib/dqt/api/v1/qualified_teaching_status.rb#L33 is set to `true`, instead of `first_item[:activeAlert]`

**Comment by nomasprime** [comment]
Hi @ethanmills. Thanks for reporting these.

Currently first feature using the client's in review so will raise these simultaneously.

`active_alert` was intentional but should be updated now.

The `ni` bug looks valid but quite surprised because none of the specs and testing around this or the feature have picked this up. I'll investigate further and report back.

**Comment by nomasprime** [comment]
Bug has been raised but doesn't effect feature we're currently building on top because we rely on TRN.

We'll hopefully get to this and `active_alert` in the next sprint.

PRs welcome 🙂

**Comment by nomasprime** [comment]
Thought the API was going to be updated to be more consistent, but looks like it either hasn't happened or it's reverted.

Created a [PR](https://github.com/DFE-Digital/claim-additional-payments-for-teaching/pull/1670) for the client to use `ni` instead.
